// Liste des sentiments avec leurs émoticônes correspondantes
final Map<String, String> moodIcons = {
  'happy': '😊',
  'sad': '😢',
  'angry': '😡',
  'surprised': '😮',
  'neutral': '😐',
  'excited': '🤩',
  'bored': '😒',
  'confused': '😕',
  'content': '😌',
  'curious': '🤔',
  'disappointed': '😞',
  'embarrassed': '😳',
  'frustrated': '😤',
  'hopeful': '🤞',
  'in_love': '😍',
  'jealous': '😒',
  'nervous': '😬',
  'proud': '😏',
  'relaxed': '😌',
  'scared': '😱',
  'shocked': '😲',
  'sick': '🤢',
  'sleepy': '😴',
  'stressed': '😖',
  'surprised': '😯',
  'thankful': '🙏',
  'tired': '😪',
  'worried': '😟',
  'playful': '😜',
  'angry_alt': '🤬',
  'joyful': '😁',
  'crying': '😭',
  'laughing': '😂',
  'thinking': '🤔',
  'blushing': '😊',
  'heartbroken': '💔',
  'party': '🥳',
  'suspicious': '😒',
  'nauseous': '🤢',
  'disgusted': '🤮',
  'awkward': '😬',
  'cool': '😎',
  'surprised_alt': '😲',
  'annoyed': '😠',
  'relieved': '😌',
  'smirking': '😏',
  'grinning': '😁',
  'mischievous': '😈',
  'crying_loudly': '😭',
  'victorious': '🏆',
  'meditative': '🧘',
  'praying': '🙏',
  'facepalm': '🤦',
  'shrugging': '🤷',
  'mind_blown': '🤯',
  'sleeping': '💤',
  'dreaming': '💭',
  'thinking_hard': '🤔',
  'whistling': '😗',
  'yawning': '🥱',
  'sweating': '😅',
  'puzzled': '🧐',
  'nodding': '🤝',
  'shushing': '🤫',
  'winking': '😉',
};

// final Map<String, String> moodIcons = {
//   'happy': '😊',
//   'sad': '😢',
//   'angry': '😡',
//   'surprised': '😮',
//   'neutral': '😐',
//   'excited': '🤩',
// };
